name: indexator
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  shared_preferences: ^2.3.1
  dartz: ^0.10.0-nullsafety.2
  flutter_modular: ^5.0.3
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  platform: ^3.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.0.1+3
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.svg